### ISSUE TITLE
Validate fails with comments

### ISSUE THREAD

**Issue by hellodword** [devcontainers/action#210]
https://github.com/devcontainers/action/issues/75

I guess this is not fixed:

```jsonc
{
    "name": "debug-comments",
    "id": "debug-comments",
    "version": "1.0.0",
    "description": "",
    "mounts": [
        // "source=/dev/bus/usb,target=/dev/bus/usb,type=bind,readonly"
        {
            "source": "/dev/bus/usb",
            "target": "/dev/bus/usb",
            "type": "bind"
        }
    ],
    "installsAfter": [
        "ghcr.io/devcontainers/features/common-utils"
    ]
}
```

The cli works well:

```
$ devcontainer features package -f ./src/debug-comments
@devcontainers/cli 0.56.1. Node.js v20.11.0. linux 6.6.16 x64.
Packaging single feature...
Packaged feature 'debug-comments'
```

But the action does not:

```yaml
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: 'Validate devcontainer-feature.json files'
              uses: devcontainers/action@v1
              with:
                  validate-only: 'true'
                  base-path-to-features: './src'
```

```
undefined:7
        // "source=/dev/bus/usb,target=/dev/bus/usb,type=bind,readonly"
        ^

SyntaxError: Unexpected token / in JSON at position 131
    at JSON.parse (<anonymous>)
    at /home/runner/work/_actions/devcontainers/action/v1/dist/index.js:18623:39
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/devcontainers/action/v1/dist/index.js:18485:58)
```

It seems that action uses `JSON.parse` for JSON with comments, it's not the bug of the cli.
